### ISSUE TITLE
[OT] How to handle offline users?

### ISSUE THREAD

**Issue by coodoo** [rajaraodv/redispubsub#4]
First of all, thanks for the great series of tutorials, two thumbs up!

I've got a probably off topic question, in the example, what if some of the people are offline when new chat messages are created, I would like following things to happen:

1. Send push notification to those offline users on their phones
2. When those users come back online, they shall see those messages

Would appreciate if you could point me at the right direction on how to design an architecture and toolsets to use to tackle these questions, thanks!

**Comment by hypervillain** [comment]
Hey,

repo manager seems afk these days !
Here's some reading for you ;)

http://code.flickr.net/2012/12/12/highly-available-real-time-notifications/

**Comment by coodoo** [comment]
Hey @THook, thanks for the tips, I ended up going down another direction with CRDT and it worked perfectly well :)
